jobs:
- name: build-image
  public: true
  serial: true
  plan:
  - get: bosh-manifest-generator
    resource: repository
    trigger: true
    passed: [unit-test]
  - task: run-build
    file: bosh-manifest-generator/ci/tasks/build.yml
  - put: docker-image
    params:
      build: bosh-manifest-generator
